# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WWDC Scholars 2015' do
pod 'MWPhotoBrowser', '~> 1.4.1'
end

target 'WWDC Scholars 2015Tests' do

end

